# Generated by Django 5.1.1 on 2024-10-26 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='id',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
