# Generated by Django 5.1.1 on 2024-11-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_total_amount_order_cart_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address_id',
        ),
    ]
