# Generated by Django 5.1.1 on 2024-11-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_order_address_id_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
