# Generated by Django 5.1.1 on 2024-10-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_details_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
