# Generated by Django 5.1.1 on 2024-11-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('homepage', 'homepage'), ('shoppage', 'shoppage'), ('productpage', 'productpage')], max_length=20),
        ),
    ]
