# Generated by Django 5.1.1 on 2024-11-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
