# Generated by Django 5.1.1 on 2024-12-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_address_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupons',
            table='coupons',
        ),
    ]
